import re

# Read the inject-tab.js file
with open(r'c:\Users\HP\OneDrive\Desktop\backend\extension\content\inject-tab.js', 'r', encoding='utf-8') as f:
    content = f.read()

# Add export buttons after the result div
export_buttons_html = '''
        
        <!-- Export Buttons -->
        <div style="margin-top: 2rem; display: flex; gap: 1rem; justify-content: center;">
            <button id="export-markdown-btn" style="
                background: #5624d0;
                color: white;
                border: none;
                padding: 0.75rem 1.5rem;
                border-radius: 4px;
                font-size: 15px;
                font-weight: 600;
                cursor: pointer;
                transition: background 0.2s;
            " onmouseover="this.style.background='#3b1a8c'" onmouseout="this.style.background='#5624d0'">
                📄 Export as Markdown
            </button>
            <button id="export-pdf-btn" style="
                background: #a435f0;
                color: white;
                border: none;
                padding: 0.75rem 1.5rem;
                border-radius: 4px;
                font-size: 15px;
                font-weight: 600;
                cursor: pointer;
                transition: background 0.2s;
            " onmouseover="this.style.background='#8710d8'" onmouseout="this.style.background='#a435f0'">
                📑 Export as PDF
            </button>
        </div>'''

# Find the end of the renderResult function and add export buttons before the closing backtick
pattern = r'(</div>\s*`;\s*resultDiv\.style\.display = \'block\';)'
replacement = export_buttons_html + r'\n    \1'
content = re.sub(pattern, replacement, content)

# Add the export functions at the end of the file (before the last closing brace if any)
export_functions = '''

// Export Functions
function exportAsMarkdown(data) {
    const markdown = `# Udemy AI Smart Overview

## 📝 Summary

${data.summary}

## 💻 Code Snippets

${data.code_blocks.length > 0 ? data.code_blocks.map((code, index) => `
### Code Snippet ${index + 1}

\\\`\\\`\\\`
${code}
\\\`\\\`\\\`
`).join('\\n') : 'No code snippets found in this lecture.'}

## 🎯 Key Concepts

${data.key_concepts.map(concept => `- ${concept}`).join('\\n')}

---
*Generated by Udemy AI Smart Overview Extension*
`;

    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `udemy-summary-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    console.log('[Udemy AI] Exported as Markdown');
}

async function exportAsPDF(data) {
    if (typeof jspdf === 'undefined') {
        console.log('[Udemy AI] Loading jsPDF...');
        await loadScript('https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js');
    }
    
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    
    let yPosition = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - (margin * 2);
    
    doc.setFontSize(20);
    doc.setFont(undefined, 'bold');
    doc.text('Udemy AI Smart Overview', margin, yPosition);
    yPosition += 15;
    
    doc.setFontSize(16);
    doc.text('Summary', margin, yPosition);
    yPosition += 10;
    
    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');
    const summaryLines = doc.splitTextToSize(data.summary, maxWidth);
    doc.text(summaryLines, margin, yPosition);
    yPosition += (summaryLines.length * 7) + 10;
    
    if (yPosition > 250) {
        doc.addPage();
        yPosition = 20;
    }
    
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('Code Snippets', margin, yPosition);
    yPosition += 10;
    
    doc.setFontSize(10);
    doc.setFont('courier', 'normal');
    
    if (data.code_blocks.length > 0) {
        data.code_blocks.forEach((code, index) => {
            if (yPosition > 250) {
                doc.addPage();
                yPosition = 20;
            }
            
            doc.setFont(undefined, 'bold');
            doc.text(`Code Snippet ${index + 1}:`, margin, yPosition);
            yPosition += 7;
            
            doc.setFont('courier', 'normal');
            const codeLines = doc.splitTextToSize(code, maxWidth);
            doc.text(codeLines, margin, yPosition);
            yPosition += (codeLines.length * 5) + 10;
        });
    }
    
    if (yPosition > 220) {
        doc.addPage();
        yPosition = 20;
    }
    
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('Key Concepts', margin, yPosition);
    yPosition += 10;
    
    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');
    
    data.key_concepts.forEach(concept => {
        if (yPosition > 270) {
            doc.addPage();
            yPosition = 20;
        }
        
        const conceptLines = doc.splitTextToSize(`• ${concept}`, maxWidth - 5);
        doc.text(conceptLines, margin + 5, yPosition);
        yPosition += (conceptLines.length * 7) + 3;
    });
    
    doc.save(`udemy-summary-${Date.now()}.pdf`);
    console.log('[Udemy AI] Exported as PDF');
}

function loadScript(src) {
    return new Promise((resolve, reject) => {
        const script = document.createElement('script');
        script.src = src;
        script.onload = resolve;
        script.onerror = reject;
        document.head.appendChild(script);
    });
}
'''

# Add export functions before the last line
content = content.rstrip() + export_functions

# Write back
with open(r'c:\Users\HP\OneDrive\Desktop\backend\extension\content\inject-tab.js', 'w', encoding='utf-8') as f:
    f.write(content)

print("✅ Added export buttons and functions to inject-tab.js!")
