// Export utilities for Udemy AI Extension

/**
 * Export summary as Markdown
 */
function exportAsMarkdown(data) {
    const markdown = `# Udemy AI Smart Overview

## 📝 Summary

${data.summary}

## 💻 Code Snippets

${data.code_blocks.length > 0 ? data.code_blocks.map((code, index) => `
### Code Snippet ${index + 1}

\`\`\`
${code}
\`\`\`
`).join('\n') : 'No code snippets found in this lecture.'}

## 🎯 Key Concepts

${data.key_concepts.map(concept => `- ${concept}`).join('\n')}

---
*Generated by Udemy AI Smart Overview Extension*
`;

    // Create download
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `udemy-summary-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    console.log('[Udemy AI] Exported as Markdown');
}

/**
 * Export summary as PDF using jsPDF
 */
async function exportAsPDF(data) {
    // Load jsPDF dynamically
    if (typeof jspdf === 'undefined') {
        console.log('[Udemy AI] Loading jsPDF...');
        await loadScript('https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js');
    }

    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    let yPosition = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - (margin * 2);

    // Title
    doc.setFontSize(20);
    doc.setFont(undefined, 'bold');
    doc.text('Udemy AI Smart Overview', margin, yPosition);
    yPosition += 15;

    // Summary Section
    doc.setFontSize(16);
    doc.text('📝 Summary', margin, yPosition);
    yPosition += 10;

    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');
    const summaryLines = doc.splitTextToSize(data.summary, maxWidth);
    doc.text(summaryLines, margin, yPosition);
    yPosition += (summaryLines.length * 7) + 10;

    // Check if we need a new page
    if (yPosition > 250) {
        doc.addPage();
        yPosition = 20;
    }

    // Code Snippets Section
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('💻 Code Snippets', margin, yPosition);
    yPosition += 10;

    doc.setFontSize(10);
    doc.setFont('courier', 'normal');

    if (data.code_blocks.length > 0) {
        data.code_blocks.forEach((code, index) => {
            if (yPosition > 250) {
                doc.addPage();
                yPosition = 20;
            }

            doc.setFont(undefined, 'bold');
            doc.text(`Code Snippet ${index + 1}:`, margin, yPosition);
            yPosition += 7;

            doc.setFont('courier', 'normal');
            const codeLines = doc.splitTextToSize(code, maxWidth);
            doc.text(codeLines, margin, yPosition);
            yPosition += (codeLines.length * 5) + 10;
        });
    } else {
        doc.setFont(undefined, 'italic');
        doc.text('No code snippets found in this lecture.', margin, yPosition);
        yPosition += 10;
    }

    // Key Concepts Section
    if (yPosition > 220) {
        doc.addPage();
        yPosition = 20;
    }

    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('🎯 Key Concepts', margin, yPosition);
    yPosition += 10;

    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');

    data.key_concepts.forEach(concept => {
        if (yPosition > 270) {
            doc.addPage();
            yPosition = 20;
        }

        const conceptLines = doc.splitTextToSize(`• ${concept}`, maxWidth - 5);
        doc.text(conceptLines, margin + 5, yPosition);
        yPosition += (conceptLines.length * 7) + 3;
    });

    // Save PDF
    doc.save(`udemy-summary-${Date.now()}.pdf`);
    console.log('[Udemy AI] Exported as PDF');
}

/**
 * Helper function to load external scripts
 */
function loadScript(src) {
    return new Promise((resolve, reject) => {
        const script = document.createElement('script');
        script.src = src;
        script.onload = resolve;
        script.onerror = reject;
        document.head.appendChild(script);
    });
}
